### ISSUE TITLE
Taking screenshot in afterTest hook throwing error

### ISSUE THREAD

**Issue by Antict** [jemishgopani/wdio-mochawesome-reporter#51]
## Problem
I'm creating a screenshot in the WebdriverIO afterTest hook:
```
afterTest: function (test) {
    browser.saveScreenshot(filepath)
}
```
Then this error is thrown:
```
TypeError: this.context.push is not a function
    at module.exports.addScreenshotContext 
    at WdioMochawesomeReporter.onAfterCommand 
    at reporters.forEach.reporter 
    at Array.forEach 
    at BaseReporter.emit 
    at EventEmitter.browser.on.result 
    at Object.afterTest
```

Because of the mochawesome reporter it's impossible to create a screenshot in the afterTest hook. This would be the place where one would create screenshots on test failure.
## Reason
I looked into the source code and found out that `addScreenshotContext` adds an object to `this.context`:
```
this.context.push({
    title: 'Screenshot',
    value: `data:image/jpeg;base64,${value}`
})
```
But at the time this method is called, `this.context` is already stringified. Thus this.`context.push` is not a function.
```
onTestEnd (test) {
    this.currTest.duration = test._duration
    this.currTest.updateResult(test)
    this.currTest.context = JSON.stringify(this.currTest.context)
    this.currSuite.addTest(this.currTest)
    this.results.stats.incrementTests(this.currTest)
}
```

**Comment by drptbl** [comment]
@Antict this works for me:
```
  afterTest: function(test) {
    if (test.error !== undefined) {
      browser.takeScreenshot();
    }
```

**Comment by Antict** [comment]
@drptbl For me it doesn't. Have you added mochawesome to your reporters array in the wdio configuration?
```
reporters: [
    ['mochawesome', {
        outputDir: './reports/mocha-results/',
        outputFileFormat: function(opts) {
            return `mochawesome-result-${opts.cid}.json`
        },
        stdout: false
     }]
]
```

**Comment by mgrybyk** [comment]
afterTest hooks signature has extended a bit in latest wdio v5 versions
```
afterTest: function(test, context, result) {
}
```

The context is mocha's this, I think it might be be useful.
