### ISSUE TITLE
unable to install the package 

### ISSUE THREAD

**Issue by amrsa1** [jemishgopani/wdio-mochawesome-reporter#62]
![image](https://user-images.githubusercontent.com/32042806/113567921-cfce1f00-960f-11eb-8dae-906b73381eac.png)

**Comment by arnisgustins** [comment]
I have seen this myself.\
One solution, while this is not solved is to install with `--force` option, but that's probably not a great idea.\
And by some reason it installed version 2.0.1 by default in my case, which is very old. Had specify version 4.0.0 when installing this dependency.

**Comment by fijijavis** [comment]
@Amrkamel1 @arnisgustins 

Yeah, this error is because of the defined peer dependencies in `package.json`.  That was the last known compatible version of WDIO.  I think the next step would be to bump the dependency and see if things still work.

**Comment by fijijavis** [comment]
Investigation Notes:
* Fresh install of `@wdio/cli` and running `npx wdio config` does not run into the above error.

**Comment by KishorGaneshrao** [comment]
Hi @fijijavis, 
Fresh install of `@wdio/cli` doesn't seem to be working. Is there a plan to bump up the WDIO dependency to latest version?
Thanks.

Regards,
Kishor Ganeshrao

**Comment by MattKeenum** [comment]
@fijijavis This did not work. Is there a plan to up the dependency?

**Comment by chamo7ac** [comment]
+1 keen to have this updated please
