### ISSUE TITLE
Not able to generate .json files after adding the dependencies for mochawesome reporter

### ISSUE THREAD

**Issue by euexplorer** [jemishgopani/wdio-mochawesome-reporter#77]
Hi, I have added below dependencies to my project "@wdio/dot-reporter": "^7.16.14", "@wdio/mocha-framework": "6.10.11", "wdio-mochawesome-reporter": "^4.0.0", "mochawesome": "^7.0.1", "mochawesome-report-generator": "^6.0.1",

Now my wdio config looks like 
reporters: [
    'spec',
    [
      'mochawesome',
      {
        outputDir: 'mochawesome-results',
      },
    ],
  ],

on running a spec file. I can see the folder is getting created of results but it has only wdio-0-0-mochawesome-reporter.log file and no json file. Please let me know what is missing?

**Comment by peterdutton** [comment]
I have the same issue, were you able to solve this?
